# Created with YamlCreate.ps1 v2.2.9 $debug=AUSU.CRLF.5-1-19041-3031.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Dell.DisplayManager
PackageVersion: "1.56"
PackageLocale: en-US
Publisher: Dell Inc.
PublisherUrl: https://www.dell.com
PublisherSupportUrl: https://www.dell.com/support
PrivacyUrl: https://www.dell.com/privacy
# Author:
PackageName: Dell Display Manager
PackageUrl: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=m33cg
License: Proprietary
LicenseUrl: https://www.dell.com/learn/us/en/uscorp1/terms-of-sale-consumer-license-agreements
# Copyright:
# CopyrightUrl:
ShortDescription: Dell Display Manager enhances everyday productivity through comprehensive management tools giving you optimal front of screen experience, efficient display management and easy, effortless multitasking.
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
