PackageIdentifier: Dell.DisplayManager
PackageVersion: 1.56.2110
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://dl.dell.com/FOLDER09067004M/1/ddmsetup2110.exe
  InstallerSha256: 5b868f338451be1498124f7b1363a53af9c8085081a17de488d718f4d0f2c770
  Scope: machine
  InstallerSwitches:
    InstallLocation: /DIR=<INSTALLPATH>
    Silent: /VerySilent
  UpgradeBehavior: install
  ProductCode: Dell Display Manager 1.56
  AppsAndFeaturesEntries:
  - DisplayName: Dell Display Manager 1.56
    DisplayVersion: 1.56.2110
    ProductCode: Dell Display Manager 1.56
  DisplayInstallWarnings: false
  ReleaseDate: 2022-10-04
ManifestType: installer
ManifestVersion: 1.5.0
